name: Create repository
description: Create a new repository for a package
title: "[Create repo]: _reponame_"
labels: ["create", "repo"]
assignees: ["superuser-marty-me-uk"]
body:
  - type: markdown
    attributes:
      value: |
        Enter the name for your repository and then what you want
  - type: input
    id: repo-name
    attributes:
      label: Short description
      description: Short description for your repo
  - type: checkboxes
    attributes:
      label: Requirements
      description: Select the third party projects to utilise
      options:
        - label: I want django!
        - label: I want channels
        - label: I want a psycho database (postgresql)
        - label: I also want awesomeness!
          value: true
